# Generated by Django 4.2.5 on 2024-06-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_remove_loanapplication_supervisor_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Loan'), ('approved', 'Approved Loan'), ('approved_employee', 'Approved by Employee'), ('denied', 'Denied Loan')], default='pending', max_length=20),
        ),
    ]
